### ISSUE TITLE
AudioPackFormatHOA::create() : Id issue

### ISSUE THREAD

**Issue by AudeBodin** [IRT-Open-Source/libadm#47]
Hello,
I encounter an issue while creating programs with HOA content with the lib.
If using AudioPackFormatHOA::create() , the first pack gets automatically the Id AP_00040000.
In the ADM ITU recommandation BS.2076, it is specified that the XXXX value in AP_YYYYXXXX should start at 0001.  
Thanks!

**Comment by mikedevnull** [comment]
Hi Aude,

thank you for taking the time to file this issue and considering our library.

I think the main problem here might be that the pack, like all other elements in the library,
needs to be added to an `adm::Document` to get a meaningful Id.
This is essentially on purpose, as it's otherwise impossible to determine which other Ids are already in use, especially when elements reference each other.

If you want to, you're can manually assign any Id to the pack format using the setter method, but then it's your responsibility to ensure that this Id does not collide with any other pack format.

The following code snippet might help to highlight what I mean:
```cpp
#include <adm/adm.hpp>
#include <iostream>
int main()
{
    auto pack = adm::AudioPackFormatHoa::create(adm::AudioPackFormatName{"MyPackFormat"});

    std::cout << adm::formatId(pack->get<adm::AudioPackFormatId>()) << std::endl;
    // Output: AP_00000000

    // auto assign by adm::Document
    auto doc = adm::Document::create();
    doc->add(pack);
    std::cout << adm::formatId(pack->get<adm::AudioPackFormatId>()) << std::endl;
    // Output: AP_00041001

    // manual assignment, use with care
    auto targetId = adm::parseAudioPackFormatId("AP_00041010");
    auto anotherPack = adm::AudioPackFormatHoa::create(adm::AudioPackFormatName{"AnotherPackFormat"});
    anotherPack->set(targetId);
    std::cout << adm::formatId(anotherPack->get<adm::AudioPackFormatId>()) << std::endl;
    // Output: AP_00041010
}
```

More information about the automatic Id assignment can be found in the tutorial section of the documentation: https://libadm.readthedocs.io/

Please let me know if this solves your problem and I can close this issue.

If not, it would be great if you code provide some short code snippet so I can recreate the issue on my machine.

**Comment by AudeBodin** [comment]
Hello Michael,

Thank you for your clear and detailed answer. Unfortunalty it doesn't fix my issue.
I think my pack was already added to the document because of the references made. I tried to add another "admDocument->add(pack)" but the issue is still there. In the debugger, I watched the pack just after adding it the document, as you suggest it, but the id stayed the same, as you can see in the next figure. The pack is declared outside of this "if" loop, as a "std::shared_ptr<AudioPackFormat>" . I already had the issue when it was declared as a "std::shared_ptr<AudioPackFormatHoa>" .

![Code snipped](https://user-images.githubusercontent.com/25790197/82309448-704d2d80-99c3-11ea-81fe-b82237365877.PNG)

I use the same implementation for adding DirectChannel packs to my file. The only difference regarding the pack is the "audioPackFormat::create()" for DirectChannels, and "audioPackFormatHoa;;create()" for HOA.  The Id are well assigned for the DirectChannel packs.
Here's how I do:

I first create a Document by using:
"std::shared_ptr<Document>admDocument= Document::create();"
Then I create a bunch of adm::AudioObjects depending on the config that was previoulsy selected. 
I chose the normalization, the TypeDefinition::HOA.
For example for the config 8 (Order 0), I have the following code : 
![My_code](https://user-images.githubusercontent.com/25790197/82307609-e2704300-99c0-11ea-9a0c-1adc0733a657.PNG)
If it is the first object with this config, then I create a Pack for this configuration. I had the reference on the corresponding channel. I had the reference of the pack to the adm::AudioObject (named "bed"), previoulsy created.
Later on , I create an audio Content that references this adm::AudioObject, and then an audioProgramme that references this audioContent. After that, I had the audioProgramme to the admDocument.
I hope it's clear enough ! 
Thank you for your time and consideration

**Comment by mikedevnull** [comment]
Hi Aude,

thanks for the detailed description.

I think it would be really helpful to have a minimal runnable code-snippet of the problem, just enough so it does compile and run and reproduces the problem.

I can try to do this based on your description, but this might take some time before I find the time to dive into this.

To speed things up, maybe it's possible for you to create such a minimal example (based on your current code?) and post it here?

**Comment by AudeBodin** [comment]
Hello,

I wrote a simple main file based on my code that still shows the issue. Here it is : 
[Minimal_code.txt](https://github.com/IRT-Open-Source/libadm/files/4656571/Minimal_code.txt)

Thank you for your help 
Best regards,
Aude

**Comment by mikedevnull** [comment]
Thanks for the example, this was very helpful.

I think I know what's happening here:
The "problem" is the extra `TypeDescriptor` (`TypeDefinition::HOA`) that gets passed to the `::create()` function and therefore the constructor.
A `TypeDescriptor` is not an actual property of the `AudioPackFormat` (in fact, for an `AudioPackFormatHoa`, it's already implied).
So normally I would expect this not to compile.

Unfortunately, the given type descriptor is implicitly converted to an `AudioPackFormatId`, which is set on the pack and therefore generates the `AP_00040000` id.
As the id set "manually", it will not be changed by the document when adding the pack.

Thus, the quick and short solution for you should be to simply remove the `descriptor` from the call to `AudioPackFormatHoa::create()`.
This should fix your immediate problem.

Nevertheless, we need to think about how we can prevent and catch this behaviour in the first place (there are multiple options, not entirely sure right now what's the best way to fix this).

I hope this helps?

**Comment by AudeBodin** [comment]
Hey,
Thank you, this was indeed the problem!

**Comment by AudeBodin** [comment]
Thank you very much for your help, this was indeed the problem! Issue fixed on my side

**Comment by rsjtaylor** [comment]
I suspect we should make all of the variadic constructors explicit? It never occurred to me before that in the case of them being called with a single parameter they would operate as a conversion constructor - feels dangerous as I think this means they could potentially be converted to anything.

**Comment by mikedevnull** [comment]
Yes, I agree, the constructors should be explicit. 
I was unsure if this might break something else, but everything seems to work as expected.
I'll open another issue and prepare a pull request for that.
